apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jhipster-secrets-dev
  namespace: nubenetes-dev-apps
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: hashicorp-vault-backend
    kind: ClusterSecretStore
  target:
    name: jhipster-database-credentials
  data:
    - secretKey: DB_USER
      remoteRef:
        key: secret/data/dev/jhipster
        property: username
    - secretKey: DB_PASS
      remoteRef:
        key: secret/data/dev/jhipster
        property: password
