apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jhipster-secrets-prod
  namespace: nubenetes-prod-apps
spec:
  refreshInterval: "30m"
  secretStoreRef:
    name: hashicorp-vault-backend
    kind: ClusterSecretStore
  target:
    name: jhipster-database-credentials
  data:
    - secretKey: DB_USER
      remoteRef:
        key: secret/data/prod/jhipster
        property: username
    - secretKey: DB_PASS
      remoteRef:
        key: secret/data/prod/jhipster
        property: password
